version: '3.9'
services:
  app:
    build:
      context: ./program
      dockerfile: Containerfile
    volumes:
      - ./program/app:/software/app
    # command mantendrá el contenedor en ejecución y no se cerrará después de 
    # que se inicie esto es perfecto para desarrollar dentro del contenedor 
    # con vscode
    command: sh -c "python app/program.py && tail -f /dev/null"
    # docker-compose exec app python app/program.py

