apiVersion: apps/v1
kind: Deployment
metadata:
  name: nombre-de-tu-aplicacion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nombre-de-tu-aplicacion
  template:
    metadata:
      labels:
        app: nombre-de-tu-aplicacion
    spec:
      containers:
        - name: nombre-de-tu-aplicacion-container
          image: tu-repo/tu-aplicacion:latest  # Reemplaza con la ubicación de tu imagen de Docker
          ports:
            - containerPort: 8000  # Reemplaza con el puerto correcto
          resources:
            limits:
              memory: "1Gi"  # Límite máximo de uso de RAM
