apiVersion: v1
kind: Service
metadata:
  name: nombre-de-tu-aplicacion-service
spec:
  selector:
    app: nombre-de-tu-aplicacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Reemplaza con el puerto correcto
  type: LoadBalancer  # Esto depende de tu entorno, puede ser ClusterIP o NodePort
